name: Deploy Action
on:
  workflow_dispatch:
    inputs:
      PJ:
        description: 'PJ'
        required: true
        type: choice
        options:
          - hoge
          - piyo
          - fuga
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
      - name: Check requirement
        shell: pwsh
        run: |
          Get-Location | Write-Output
          Get-ChildItem | Write-Output
          ${$GITHUB_WORKSPACE}\.github\scripts\deploy.ps1 ${{ github.event.inputs.PJ }}
