name: Test
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - develop
      - release
      - main
    paths:
      - "*"
      - src/**
      - "!**.md"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "Hello Ohayou"

