name: tutorial
on: [push]
jobs:
  command:
    name: Use Linux commands
    runs-on: ubuntu-latest
    steps:
      - name: Show ubuntu details
        run: lsb_release -a
      - name: Make test dir Kanikama
        run: mkdir Kanikama
      - name: show files
        run: ls -la
      - name: Checkout
        run: cd Kanikama 
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Inspect files after checkout
        run: ls -la
      - name: show all branches after checkout
        run: git branch -a
      - name: check git tracking
        run: git status